### ISSUE TITLE
stashbot will not create builds when jenkins CSRF protection is active

### ISSUE THREAD

**Issue by memory** [terabyte/stashbot#13]
Stacktrace: 

```
2015-11-09 14:53:45,283 ERROR [http-nio-7991-exec-100] n @9ISZQWx893x2627211x1 1woavlg 127.0.0.1 "POST /plugins/servlet/stashbot/repo-admin/SRE/instancelib HTTP/1.0" c.p.s.s.managers.JenkinsManager Exception while attempting to create missing jobs for a repo:
java.lang.RuntimeException: Exception while attempting to get/vivify folder chain
        at com.palantir.stash.stashbot.managers.JenkinsManager.getOrCreateFolderJob(JenkinsManager.java:202) ~[stashbot-1.3.8-63-g9b057047f8d5_1447080661000.jar:na]
        at com.palantir.stash.stashbot.managers.JenkinsManager.getPrefixFolderJob(JenkinsManager.java:225) ~[stashbot-1.3.8-63-g9b057047f8d5_1447080661000.jar:na]
        at com.palantir.stash.stashbot.managers.JenkinsManager.access$100(JenkinsManager.java:67) ~[stashbot-1.3.8-63-g9b057047f8d5_1447080661000.jar:na]
        at com.palantir.stash.stashbot.managers.JenkinsManager$UpdateAllRepositoryVisitor.call(JenkinsManager.java:640) ~[stashbot-1.3.8-63-g9b057047f8d5_1447080661000.jar:na]
        at com.palantir.stash.stashbot.managers.JenkinsManager$UpdateAllRepositoryVisitor.call(JenkinsManager.java:606) ~[stashbot-1.3.8-63-g9b057047f8d5_1447080661000.jar:na]
        at com.palantir.stash.stashbot.managers.JenkinsManager.updateRepo(JenkinsManager.java:172) ~[stashbot-1.3.8-63-g9b057047f8d5_1447080661000.jar:na]
        at com.palantir.stash.stashbot.servlet.RepoConfigurationServlet.doPost(RepoConfigurationServlet.java:265) [stashbot-1.3.8-63-g9b057047f8d5_1447080661000.jar:na]
        at com.atlassian.applinks.core.rest.context.ContextFilter.doFilter(ContextFilter.java:25) [applinks-plugin-4.3.7_1436762744000.jar:na]
        at com.opensymphony.sitemesh.webapp.SiteMeshFilter.obtainContent(SiteMeshFilter.java:181) [sitemesh-2.5-atlassian-11.jar:na]
        at com.opensymphony.sitemesh.webapp.SiteMeshFilter.doFilter(SiteMeshFilter.java:85) [sitemesh-2.5-atlassian-11.jar:na]
        at com.atlassian.stash.internal.spring.security.StashAuthenticationFilter.doFilter(StashAuthenticationFilter.java:88) [StashAuthenticationFilter.class:na]
        at com.atlassian.stash.internal.web.auth.BeforeLoginPluginAuthenticationFilter.doInsideSpringSecurityChain(BeforeLoginPluginAuthenticationFilter.java:109) [BeforeLoginPluginAuthenticationFilter.class:na]
        at com.atlassian.stash.internal.web.auth.BeforeLoginPluginAuthenticationFilter.doFilter(BeforeLoginPluginAuthenticationFilter.java:75) [BeforeLoginPluginAuthenticationFilter.class:na]
        at com.atlassian.security.auth.trustedapps.filter.TrustedApplicationsFilter.doFilter(TrustedApplicationsFilter.java:103) [atlassian-trusted-apps-core-4.0.0.jar:na]
        at com.atlassian.oauth.serviceprovider.internal.servlet.OAuthFilter.doFilter(OAuthFilter.java:79) [atlassian-oauth-service-provider-plugin-1.9.10_1432252388000.jar:na]
        at com.atlassian.analytics.client.filter.DefaultAnalyticsFilter.doFilter(DefaultAnalyticsFilter.java:36) [analytics-client-3.70.1_1436168808000.jar:na]
        at com.atlassian.analytics.client.filter.AbstractHttpFilter.doFilter(AbstractHttpFilter.java:32) [analytics-client-3.70.1_1436168808000.jar:na]
        at com.atlassian.stash.internal.web.auth.BeforeLoginPluginAuthenticationFilter.doBeforeBeforeLoginFilters(BeforeLoginPluginAuthenticationFilter.java:87) [BeforeLoginPluginAuthenticationFilter.class:na]
        at com.atlassian.stash.internal.web.auth.BeforeLoginPluginAuthenticationFilter.doFilter(BeforeLoginPluginAuthenticationFilter.java:73) [BeforeLoginPluginAuthenticationFilter.class:na]
        at com.atlassian.stash.internal.request.DefaultRequestManager.doAsRequest(DefaultRequestManager.java:85) [stash-service-impl-3.11.1.jar:na]
        at com.atlassian.stash.internal.hazelcast.ConfigurableWebFilter.doFilter(ConfigurableWebFilter.java:38) [ConfigurableWebFilter.class:na]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_45]
        at java.lang.Thread.run(Thread.java:745) [na:1.8.0_45]
        ... 186 frames trimmed
Caused by: org.apache.http.client.HttpResponseException: No valid crumb was included in the request
        at com.offbytwo.jenkins.client.validator.HttpResponseValidator.validateResponse(HttpResponseValidator.java:11) ~[stashbot-1.3.8-63-g9b057047f8d5_1447080661000.jar:na]
        at com.offbytwo.jenkins.client.JenkinsHttpClient.post_form(JenkinsHttpClient.java:284) ~[stashbot-1.3.8-63-g9b057047f8d5_1447080661000.jar:na]
        at com.offbytwo.jenkins.JenkinsServer.createFolder(JenkinsServer.java:373) ~[stashbot-1.3.8-63-g9b057047f8d5_1447080661000.jar:na]
        at com.offbytwo.jenkins.JenkinsServer.createFolder(JenkinsServer.java:354) ~[stashbot-1.3.8-63-g9b057047f8d5_1447080661000.jar:na]
```

Such documentation as seems to exist on the jenkins CSRF API: 
- https://wiki.jenkins-ci.org/display/JENKINS/Remote+access+API
- https://issues.jenkins-ci.org/browse/JENKINS-15252

**Comment by terabyte** [comment]
Most calls to the jenkins-client library take a boolean value called "crumbFlag" to override whether or not they should try to get crumbs and include them.
- If passing "true" when CSRF is disabled causes no problems, we should always pass true
- in the past, this did not work, and at palantir we had it off, so I had to manually pass false
- if that is still the case, we need to detect whether it is on or not, and use the correct value
- -OR- fix jenkins-client library.
